packages:
  - "pi-form-components"
  - "pi-bash-tooljack-nu"
  - "pi-agent-resource"
  - "internal/*"
  - "tools/pi-generators"
  - "pi-prompt-guard"
allowBuilds:
  '@biomejs/biome': true
  '@google/genai': true
  '@swc/core': true
  esbuild: true
  koffi: true
  nx: true
  protobufjs: true
